hash-format = "sha256"

[[files]]
file = "mods/c2me-fabric.pw.toml"
hash = "78bf078da5e46c2513889f86aa24e522d0651055b5a93a17341b96fdcba70b5e"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "b6348f94ec939f563285dc96683e61da8fc17ab2f2897be2751fa24789513691"
metafile = true

[[files]]
file = "mods/collective.pw.toml"
hash = "204b3eb115e418bdad4f5f2e8ef49f0c8b8f10ad062ca10e05e1e8cde4de45ab"
metafile = true

[[files]]
file = "mods/double-doors.pw.toml"
hash = "c02a955a040a1ecdfdbe9573ffd0c5a252c51560871f068becbcfd713b386b16"
metafile = true

[[files]]
file = "mods/ebe.pw.toml"
hash = "b8270928d44781b9e59982d376bb3cc0d24089ceebef3c79d3e1e881ba7ece60"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "4eec3de8a58a6e64ea96e31781b52f70b4b33ec02a34a45f171e3a1e6697ba86"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "901f5e42d26508230a41b6f91e1da18910b201aa3730057853d135820f24ec8c"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "03e174cf691b52da20bd973b955fae6f3720d3d2120f9d6cc1de5fdf3180013c"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "a154087f80d2179cabd05cf7629c29c06c5a62538e70f7c58021dd1d4f9e3e3a"
metafile = true

[[files]]
file = "mods/indium.pw.toml"
hash = "85daf558c36022a664c9e2bc3d9a9bc21cb9fa62977890f142c20ccc155eae36"
metafile = true

[[files]]
file = "mods/inventory-sorting.pw.toml"
hash = "82a7c9721c81c309d3c4dc2cf93ab12e1399894d03b738782ac04b0b7c232213"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
hash = "71ef7cc16632c0039fe194183b5885968c6d740aaa67a58000653ae0cb40b882"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "c239c951796882b9c93e649a0dba4f2d95804441faaed707b686381b7a5c67da"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
hash = "b069be03cd4e76ff934e079cb3103101dba440ad9343b904967b06fc8a075e0f"
metafile = true

[[files]]
file = "mods/mods-command.pw.toml"
hash = "d09ddd35158bc690b235adc42c84b62172c6ef0ec45fa45589b290c0233af4f4"
metafile = true

[[files]]
file = "mods/moreculling.pw.toml"
hash = "6d813994b3eda187ae08b36561b60205de365852e2163f323c4c0ee283816ac6"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
hash = "7ca62a9da5c2ec9f0a8bed5394021c959e90077db16b313be44f4c8736f7fbf5"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "217b07516517c4c01958387192143943f3e9309a0e935828f9f32af771425d66"
metafile = true

[[files]]
file = "mods/threadtweak.pw.toml"
hash = "bb044cd95d56fb9e1f52a8c18a843df8daf56d22a822568112e9dfa28dab7926"
metafile = true

[[files]]
file = "mods/vmp-fabric.pw.toml"
hash = "dc3970e3d66599050e917319f42a8a002f2ec0ed744d3140acc5a6f3d032199f"
metafile = true

[[files]]
file = "mods/your-items-are-safe.pw.toml"
hash = "e9fc99724fb2d5cb665005dffda212cd331e0df312b4bfea824ae3aba58c3ad5"
metafile = true
